# Generated by Django 6.1.1 on 2026-09-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
